In [3]:
import numpy as np
np.__version__

'1.14.3'

# Concatenando Arrays

In [4]:
array1 = np.ones(4)

In [5]:
array2= np.arange(15)

In [8]:
array_conca = np.concatenate((array1,array2))

In [9]:
array_conca

array([ 1.,  1.,  1.,  1.,  0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,
        9., 10., 11., 12., 13., 14.])

# Join de Arrays

In [20]:
a = np.ones((3,3))

In [21]:
b = np.zeros((3,3))

In [12]:
print(a)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [13]:
print(b)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [15]:
#visualizando a documentacao de uma funcao
#empilha um array em nivel vertical
?np.vstack

In [16]:
?np.hstack

In [17]:
#juncao a nivel vertical
np.vstack((a,b))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [18]:
#juncao a nivel horizontal
np.hstack((a,b))

array([[1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0.]])

In [33]:
#Join arrays
a1 = np.array([0,1,2])
b1 = np.array([4,5,6])


In [34]:
#funcao que concatena array de 1 dimensao como coluna
np.column_stack((a1,b1))

array([[0, 4],
       [1, 5],
       [2, 6]])

In [35]:
np.row_stack((a,b))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

# Split de Array

In [36]:
#cria um array com dimensao 4,4
a3 = np.arange(16).reshape((4,4));

In [37]:
a3

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [38]:
#fatiamento em nivel horizontal
a3_split1,a3_split2 = np.hsplit(a3,2)

In [41]:
a3_split1

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [42]:
a3_split2

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

# Salvar dados com numpy

In [43]:
#salva o objeto array para ser consumido posteriormente
np.save('array_xpto',a3_split1)

In [44]:
load_Array = np.load('array_xpto.npy')

In [45]:
load_Array

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])