# Computação com Numpy

## Parte 1

In [1]:
#Import do modulo
import numpy as np

In [2]:
#array unidimensional
array1 = np.array([10,20,30,40])
array1

array([10, 20, 30, 40])

In [4]:
#array bi-dimensional
array2 = np.array([[100,200,300],[400,500,500]])
array2

array([[100, 200, 300],
       [400, 500, 500]])

In [7]:
#verificando shape(formato) do array
print(array1.shape)
print(array2.shape)

(4,)
(2, 3)


In [11]:
# atributo para verificar numero de dimensoes
array1.ndim

1

In [9]:
array2.ndim

2

## Parte 2

In [10]:
#metodo obtem maior elemento do array
array2.max()

500

In [53]:
#cria estrutura de elementos com arange
array3 = np.arange(15,dtype='float')

In [54]:
array3

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14.])

In [18]:
#cria estrutura de elementos com start/end (exclusivo)
#(ini,fim, salto)
array4 = np.arange(0,15,5); array4

array([ 0,  5, 10])

In [21]:
#cria estrutura de elementos com linspace
array5 = np.linspace(0,3,4);array5

array([0., 1., 2., 3.])

## Estrutura de dados com outras funções

In [22]:
#array multidimensional
array6 = np.zeros((10,8));array6

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

## np.ones

In [31]:
#array 2x3x2 ->  2 dimensões de array 2x3
array7 = np.ones((2,3,3));array7

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

## np.eye

In [32]:
#matriz identidade
array8 = np.eye(3);array8

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## np.diag

In [33]:
#matriz diagonal
array9 = np.diag((1,2,3,4));array9

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

## np.random.rand

In [38]:
#cria elementos aleatorios distribuidos uniformemente de 0 a n
#no caso, 5 valores aleatorios
array10 = np.random.rand(5);array10

array([0.29919369, 0.51206848, 0.08725092, 0.94160254, 0.76200238])

## np.tile

In [43]:
array12 = np.array([1,2,3]);array12

array([1, 2, 3])

In [45]:
#repete o array em um numero de vezes unidimensionalmente especificado
np.tile(array12,2)

array([1, 2, 3, 1, 2, 3])

In [52]:
#repete o array em um numero de vezes bidimensionalmente especificado
np.tile(array12,(2,1))

array([[1, 2, 3],
       [1, 2, 3]])

In [61]:
array13 = np.array((10.5,11));array13

array([10.5, 11. ])

In [62]:
#exibe o tipo de dado do array
array13.dtype

dtype('float64')

In [63]:
#converte o tipo de dado
array13.astype(int)

array([10, 11])

## Operações com Arrays

In [66]:
#multiplicacao
array14 = np.arange(0,10) * 5 ; array14

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [68]:
array15 = np.array((10,20,30));array15

array([10, 20, 30])

In [71]:
array16 = np.array((5,10,35));array16

array([ 5, 10, 35])

In [72]:
#subtracao
array15 - array16

array([ 5, 10, -5])

In [74]:
#comparacao de valores
array15 > array16

array([ True,  True, False])

In [75]:
array_teste1 = np.arange(1000)
%timeit array_teste1 ** 4

8.97 µs ± 770 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [77]:
array_teste2 = range(1000)
%timeit [ array_teste2[i] ** 4 for i in array_teste2 ]

622 µs ± 13.5 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [ ]:
# %timeit - obtem o tempo de execução da instrução, o % é o jupyter